Query Update
I never managed to solve this issue, which is why I never rendered anything:
"compilation failed- error
Package graphics Error: Division by 0.

See the graphics package documentation for explanation."